/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestform;

import java.sql.*;
import javax.swing.*;
   /*
 *
 * @author z
 */
public class LoginFrame extends javax.swing.JFrame {
    private JTextField userChamp;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JButton conButton;
    private JLabel jLabel3;
    private JPasswordField mdpChamp;
    private JLabel infoLab;
    private JLabel jLabel4;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userChamp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        conButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mdpChamp = new javax.swing.JPasswordField();
        infoLab = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        userChamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userChampActionPerformed(evt);
            }
        });
        getContentPane().add(userChamp);
        userChamp.setBounds(210, 140, 93, 28);

        jLabel1.setText("Utilisateur :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 140, 73, 16);

        jLabel2.setText("Mot de passe :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 180, 91, 16);

        conButton.setText("Se connecter");
        conButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conButtonActionPerformed(evt);
            }
        });
        getContentPane().add(conButton);
        conButton.setBounds(170, 210, 124, 29);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 53, 0, 0);
        getContentPane().add(mdpChamp);
        mdpChamp.setBounds(210, 180, 150, 28);

        infoLab.setText("Bienvenue à la Maison des Ligues de Lorraine");
        getContentPane().add(infoLab);
        infoLab.setBounds(70, 350, 290, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Applications/MAMP/htdocs/site/images/logom2l.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 40, 240, 300);

        setBounds(0, 0, 412, 424);
    }// </editor-fold>//GEN-END:initComponents

    private void userChampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userChampActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_userChampActionPerformed

    private void conButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conButtonActionPerformed
PreparedStatement St = null;
           String login = userChamp.getText();
           String password = mdpChamp.getText();
           String sql;
           ResultSet Rs = null;
            St=null;
           try{///chaine de conection avec BD Mysql
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection cnx =    DriverManager.getConnection("jdbc:mysql://82.127.32.30:3306/veyre_ppe2","root", "root"); 
                          sql = "SELECT nLicence FROM ADHERENT WHERE username= ? AND password = ?";
                      St = (PreparedStatement) cnx.prepareStatement(sql);
                      St.setString(1, login);
                      St.setString(2, password);
                      Rs = St.executeQuery();
                   
                    if   (!Rs.next()) {
                        sql = "SELECT idOrganisateur FROM ORGANISATEUR WHERE username= ? AND password = ?";
                      St = (PreparedStatement) cnx.prepareStatement(sql);
                      St.setString(1, login);
                      St.setString(2, password);
                      Rs = St.executeQuery();
                            
                                if   (!Rs.next()) {
                                    infoLab.setText("echec d'autentification");

                                }
                                else {
                                    GESTFORM.id=Rs.getString(1);
                                    GESTFORM.org=true;
                                    
        this.dispose();// fermer la frame courante
        //this.setVisible(false);// fermer la frame courante auth
       new orgFrame().setVisible(true);// ouvre la frame principale
   }  
                    }
                     else {
                        GESTFORM.id=Rs.getString(1);
                                    GESTFORM.org=false;
        this.dispose();// fermer la frame courante
        //this.setVisible(false);// fermer la frame courante auth
       new mainFrame().setVisible(true);// ouvre la frame principale
   }  
    
                          }
                        catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Authentification Echouer" +e.getMessage());
                        }    // TODO add your handling code here:
    }        // TODO add your handling code here:
        
    }//GEN-LAST:event_conButtonActionPerformed

    /**
     * @param args the command line arguments
     */
  
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conButton;
    private javax.swing.JLabel infoLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField mdpChamp;
    private javax.swing.JTextField userChamp;
    // End of variables declaration//GEN-END:variables
*/
